import { StyleSheet } from "react-native";
import { Platform } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingHorizontal: 15,
    paddingBottom: 15,
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
    marginTop: -50,
  },
  backButton: {
    padding: 5,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginLeft: 15,
  },
  section: {
    padding: 15,
    backgroundColor: "#FFF",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    color: "#333",
  },
  inputContainer: {
    marginBottom: 20,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    backgroundColor: "#FFF",
  },
  addressSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 48,
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: "#FFF",
    marginBottom: 20,
  },
  addressText: {
    fontSize: 16,
    color: "#333",
    flex: 1,
    marginRight: 10,
  },
  placeholderText: {
    color: "#999",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    maxHeight: "50%",
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  addressItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#EEE",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  addressItemText: {
    fontSize: 16,
    color: "#333",
    flex: 1,
  },
  defaultBadge: {
    fontSize: 12,
    color: "#FFF",
    backgroundColor: "#F28C38",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  voucherContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  voucherInput: {
    flex: 1,
    marginRight: 10,
  },
  applyVoucherButton: {
    backgroundColor: "#F28C38",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    justifyContent: "center",
    height: 48, // Đảm bảo cùng chiều cao với ô nhập
  },
  applyVoucherText: {
    fontSize: 16,
    color: "#FFF",
    fontWeight: "bold",
    textAlign: "center",
  },
  paymentOption: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  paymentText: {
    fontSize: 16,
    marginLeft: 10,
    color: "#333",
  },
  orderList: {
    flexGrow: 1,
    backgroundColor: "#FFF",
    paddingBottom: Platform.OS === "ios" ? 0 : 20,
  },
  orderItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 15,
    backgroundColor: "#FFF",
    borderRadius: 8,
    marginHorizontal: 15,
    marginBottom: 10,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  itemName: {
    fontSize: 16,
    fontWeight: "500",
    flex: 2,
    color: "#333",
  },
  itemPrice: {
    fontSize: 16,
    flex: 1,
    textAlign: "center",
    color: "#666",
  },
  itemQuantity: {
    fontSize: 16,
    flex: 1,
    textAlign: "center",
    color: "#666",
  },
  itemTotal: {
    fontSize: 16,
    fontWeight: "bold",
    flex: 1,
    textAlign: "right",
    color: "#F28C38",
  },
  summary: {
    marginTop: 10,
    padding: 15,
    backgroundColor: "#FFF",
    marginHorizontal: 15,
    borderRadius: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: 16,
    color: "#666",
  },
  summaryValue: {
    fontSize: 16,
    color: "#333",
  },
  summaryTotal: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#F28C38",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 15,
    backgroundColor: "#FFF",
    paddingBottom: Platform.OS === "ios" ? 30 : 15,
  },
  backToCartButton: {
    flex: 1,
    padding: 15,
    borderWidth: 1,
    borderColor: "#F28C38",
    borderRadius: 8,
    alignItems: "center",
    marginRight: 10,
  },
  backToCartText: {
    fontSize: 16,
    color: "#F28C38",
    fontWeight: "bold",
  },
  placeOrderButton: {
    flex: 1,
    backgroundColor: "#F28C38",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  placeOrderText: {
    fontSize: 16,
    color: "#FFF",
    fontWeight: "bold",
  },
  updateButton: {
    backgroundColor: "#4CAF50",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  updateButtonText: {
    fontSize: 16,
    color: "#FFF",
    fontWeight: "bold",
  },
  disabledButton: {
    backgroundColor: "#ccc",
    opacity: 0.6,
  },
  noAddressText: {
    fontSize: 14,
    color: "#666",
    marginBottom: 10,
    textAlign: "center",
  },
  loadingText: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
    marginBottom: 10,
  },
});