import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FEF8EF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 40,
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
    marginTop: -55,
    paddingTop: 60,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FEE5C9",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  greeting: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000",
  },
  userContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 3,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  userName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
  },
  logoutButton: {
    padding: -12,
  },
  logoutText: {
    fontSize: 14,
    color: "#E57905",
    fontWeight: "bold",
  },
  ticketButton: {
    marginRight: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FEE5C9",
    justifyContent: "center",
    alignItems: "center",
  },
  notificationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  loginCard: {
    backgroundColor: "white",
    borderRadius: 16,
    marginHorizontal: 16,
    marginVertical: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#F5F5F5",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  loginCardContent: {
    padding: 16,
  },
  loginTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "left",
  },
  loginSubtitle: {
    fontSize: 14,
    textAlign: "left",
    lineHeight: 20,
    marginBottom: 20,
    color: "#777",
  },
  loginButton: {
    backgroundColor: "#E57905",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
    marginBottom: 16,
  },
  loginButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  rewardButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F6F6F6",
    borderRadius: 8,
    padding: 16,
  },
  rewardText: {
    fontWeight: "500",
    fontSize: 16,
    color: "#E57905",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 8,
    marginHorizontal: 15,
    marginVertical: 10,
    paddingHorizontal: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    padding: 10,
    fontSize: 16,
    color: "#000",
    backgroundColor: "#FFF",
  },
  searchIcon: {
    marginRight: 10,
    color: "#E57905",
  },
  serviceContainer: {
    marginVertical: 10,
    marginHorizontal: 10,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    marginTop: 20,
    elevation: 3,
  },
  serviceItem: {
    alignItems: "center",
    marginHorizontal: 10,
    marginTop: 10,
  },
  serviceIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FEE5C9",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  serviceText: {
    textAlign: "center",
    fontSize: 12,
    color: "#000",
  },
  promotionContainer: {
    marginHorizontal: 16,
    marginVertical: 10,
    alignItems: "center",
  },
  promotionBanner: {
    width: "100%",
    height: 150,
    borderRadius: 12,
    backgroundColor: "transparent",
    padding: 0,
    overflow: "hidden",
  },
  paginationDots: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 10,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#D3D3D3",
    marginHorizontal: 4,
  },
  activeDot: {
    backgroundColor: "#E57905",
    width: 16,
  },
  discoverSection: {
    marginHorizontal: 16,
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000",
  },
  viewMoreText: {
    color: "#F37934",
    fontWeight: "500",
    fontSize: 14,
  },
  offerContainer: {
    marginBottom: 15,
  },
  offerCard: {
    width: 200,
    marginRight: 10,
    backgroundColor: "#FFF",
    borderRadius: 8,
    padding: 10,
    paddingTop: 10,
    paddingBottom: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  offerSubtitle: {
    fontSize: 12,
    color: "#777",
    marginTop: 5,
  },
  offerTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginVertical: 5,
    color: "#000",
  },
  offerDateContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  offerDate: {
    fontSize: 12,
    color: "#777",
  },
  deliveryInfoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    marginTop: 10,
  },
  deliveryIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FEE5C9",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  deliveryInfoText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#000",
  },
  deliverySubtext: {
    fontSize: 14,
    fontWeight: "normal",
    color: "#777777",
  },
  productSection: {
    marginHorizontal: 16,
    marginVertical: 10,
  },
  productList: {
    flexGrow: 1,
    paddingBottom: 10,
  },
  productCard: {
    width: "48%",
    backgroundColor: "#FFF",
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  newBadge: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "#E57905",
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  newBadgeText: {
    color: "#FFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  productImage: {
    width: "100%",
    height: 120,
    borderRadius: 8,
  },
  productName: {
    fontSize: 14,
    fontWeight: "bold",
    marginVertical: 5,
    color: "#000",
  },
  productPriceContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  productPrice: {
    fontSize: 14,
    color: "#000",
  },
  addButton: {
    backgroundColor: "#E57905",
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
  },
});

export default styles;
