import { StyleSheet } from "react-native";

// Styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 25,
    backgroundColor: "#F8F9FA",
    justifyContent: "center",
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
  },
  title: {
    fontSize: 35,
    top: -37,
    left: 130,
    right: 0,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 4,
    color: "#333",
  },
  welcomeText: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 15,
    color: "#666",
    marginBottom: 25,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  icon: {
    marginRight: 100,
  },
  input: {
    flex: 1,
    fontSize: 16,
  },
  rememberContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 10,
    marginTop: 10,
  },
  rememberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  forgetText: {
    fontSize: 14,
    color: "#077F7B",
    fontWeight: "bold",
  },
  signInButton: {
    backgroundColor: "#077F7B",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginVertical: 15,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  signInText: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  signupText: {
    textAlign: "center",
    fontSize: 15,
    color: "#666",
    marginVertical: 8,
  },
  signupLink: {
    color: "#077F7B",
    fontWeight: "bold",
  },
  orText: {
    textAlign: "center",
    marginVertical: 15,
    fontSize: 15,
    fontWeight: "bold",
    color: "#888",
  },
  facebookButton: {
    flexDirection: "row",
    backgroundColor: "#4a61a8",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 5,
  },
  googleButton: {
    flexDirection: "row",
    backgroundColor: "#53a0f4",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 5,
  },
  socialText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
});
export default styles;
